### ISSUE TITLE
Update welcome before LICENSE file was removed

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/welcome#4]
Need to update `welcome` from the [2.0.20](https://github.com/EOSIO/welcome/releases/tag/v2.0.20) maintenance release to the actual point before the LICENSE file was removed (commit [ade4626](https://github.com/EOSIO/welcome/commit/b066eb0b2a397c34ba67b1e5464256f97ade4626)). Several key fixes/updates were left out (navigation restructuring, updated guides, how-tos, tutorials, etc.). These need to be added to form the absolute bare minimum to use as starting point. This is the actual [diff](https://github.com/EOSIO/welcome/compare/aab3a9b...c6b2f45) of commits before that point.

**Comment by ericpassmore** [comment]
Here are the steps you would take to accomplish this. 

# Tar file of Desired Update 
```
git clone clone https://github.com/EOSIO/welcome.git
cd welcome 
# ls -1 #you can check and see no LICENSE file
git reset --hard c6b2f45  # become the SHA you want
# ls -1  #now check and LICENSE file is there
find . -name ".git*" | xargs rm -rf   # remove git files 
cd ../
tar cvzf eosio_welcome_c6b2f45.tgz welcome
rm -rf welcome   # remove not needed 
```

# Create Branch for Updates
```
mkdir welcome   # make dir again for our version 
cd welcome 
git init
git remote add origin https://github.com/eosnetworkfoundation/welcome.git
git fetch origin --no-tags    # get history but not files 
git checkout -b updated_safe_license     # create a new branch 
cd ../
tar xvzf eosio_welcome_c6b2f45.tgz
cd welcome
git add --all
git commit     # opens editors make long commit message detailing source and license
git push origin updated_safe_license
```

# merge files 
```
rm -rf welcome    # safer to start from empty slate 
git clone https://github.com/eosnetworkfoundation/welcome.git
git tag pre_merge_updated_safe_license   # get back to good state if something goes wrong
git merge updated_safe_license
git status     # see conflicts 
# resolve merge conflicts with editor of your choice 
```

# final commit 
```
# all conflicts resolved 
git add --all 
git commit  # editor long commit message 
git push 
```

**Comment by lparisc** [comment]
Thanks Eric! I had done it already - check the new branch I pushed yesterday. Ovi was going to add the remaining commit - the one where you replace the domain name. Then I'll create a PR for your review  to merge back to main. All good, I simply created the issue for tracking purposes until we start using the git devrel project space. Thanks again.

**Comment by ericpassmore** [comment]
Summary of difference
[6b2f45-migration-diff.txt](https://github.com/eosnetworkfoundation/welcome/files/9491437/6b2f45-migration-diff.txt)
